### ISSUE TITLE
Not starting custom Version

### ISSUE THREAD

**Issue by MTRNord** [Nihlus/Launchpad#30]
I get the following Error and a 404 but in the browser It works perfect. What did I wrong? (I hope German isn't a problem otherwise I will translate it :))
`$exception	{System.NotSupportedException: Dieser Stream unterstützt keine Suchvorgänge.    
bei System.Net.ConnectStream.get_Length()    
bei Launchpad.Launcher.Handlers.Protocols.HTTPProtocolHandler.ReadRemoteFile(String URL, Boolean useAnonymousLogin)    
bei Launchpad.Launcher.Handlers.Protocols.HTTPProtocolHandler.GetRemoteLauncherVersion()    
bei Launchpad.Launcher.Handlers.Protocols.HTTPProtocolHandler.IsLauncherOutdated()    
bei Launchpad.Launcher.Handlers.ChecksHandler.IsLauncherOutdated()    
bei Launchpad.Launcher.WindowsUI.MainForm..ctor()   
 bei Launchpad.Launcher.Program.Main()}	
System.NotSupportedException`

**Comment by Nihlus** [comment]
Looks like your webserver doesn't support reporting the content length of the remote data. What are you using? LAMP/XAMP?

**Comment by Nihlus** [comment]
Have you modified the HTTPProtocolHandler class in any way?

**Comment by MTRNord** [comment]
The class is the same and the webserver is an Apache 2.4

**Comment by MTRNord** [comment]
By the way the URL is http://media.nordgedanken.de/launchpad/launcher/changelog.html

**Comment by Nihlus** [comment]
Hm. I'm not entirely sure why this is happening, then. It would seem your
webserver isn't responding with a valid Content-Length header. It works on
my end, and I'm using the same version as you are (2.4.7).

When I use your URL in my launcher, it works. Are you sure you're using the
latest version?

**Comment by MTRNord** [comment]
I will pull a fresh version fdon gihub and retry it :)

**Comment by MTRNord** [comment]
Same error with fresh version :/ I will have a look if I can get it to work on localhost

**Comment by Nihlus** [comment]
This has been fixed in #a50bf91.

**Comment by MTRNord** [comment]
Thanks :)
