### ISSUE TITLE
HTTP file grabbing not working

### ISSUE THREAD

**Issue by JoeCalvert** [Nihlus/Launchpad#33]
Launchpad is not working when grabbing by HTTP on Windows 10 64 Bit.
The window is not created so nothing is shown to user.

Screenshot of Visual Studio (Debug mode) : http://prntscr.com/b4tod8

Exception detail (Visual Studio 2015) : http://pastebin.com/2A9S73UW

**Comment by Nihlus** [comment]
Gotcha, I see the issue. Some web servers support getting the chunk length
while others do not, it seems. I'll push a patch as soon as possible.

**Comment by JoeCalvert** [comment]
Cheers. Sorry for the overload on info too, I  guess too much is better than too little.

**Comment by Nihlus** [comment]
All done :) It should work fine now, and will use the remote length property when available. When it isn't, it'll fall back to the filesize specifed in the manifest. This will only affect what's shown on the UI, and it'll always download the full file no matter what. It shouldn't differ from the manifest, but just in case it does.

**Comment by Nihlus** [comment]
Also, don't worry about adding too much information! What you had was crucial in getting this fixed so soon. Having the exception and the exact line helped a lot.

In the case of bug reports, more information is as a rule better than less information.
