### ISSUE TITLE
Suggestion: Tutorial

### ISSUE THREAD

**Issue by RenantDev** [Nihlus/Launchpad#41]
Hi!
My suggestion, create a tutorial video series .
-Installation Requirements (Win and Linux)
-Compilation
-Implementation

This tutorial helps popularize the repository.
I would like to create, but my English is bad.

**Comment by Nihlus** [comment]
I may do something like this in the future. However, all of these points are already covered in either the GitHub wiki or in source code - therefore, I'm not sure if it's really needed at this point.
