### ISSUE TITLE
MSBuild xml namespace error

### ISSUE THREAD

**Issue by lolnie** [Nihlus/Launchpad#45]
getting an error saying 

> D:\folder\Launchpad-master\Launchpad-master\Launchpad.Launcher\Launchpad.Launcher.csproj
: error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\folder\Launchpad-master\Launchpad-master\Launchpad.Launcher\Launchpad.Launcher.csproj

>D:\folder\Launchpad-master\Launchpad-master\Launchpad.Utilities\Launchpad.Utilities.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\folder\Launchpad-master\Launchpad-master\Launchpad.Utilities\Launchpad.Utilities.csproj

>D:\folder\Launchpad-master\Launchpad-master\Launchpad.Tests\Launchpad.Tests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\folder\Launchpad-master\Launchpad-master\Launchpad.Tests\Launchpad.Tests.csproj

>D:\folder\Launchpad-master\Launchpad-master\Launchpad.Common\Launchpad.Common.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\folder\Launchpad-master\Launchpad-master\Launchpad.Common\Launchpad.Common.csproj

this happens upon opening the .sln file in visual studio 2015

**Comment by Nihlus** [comment]
You need at least Visual Studio 2017.

**Comment by lolnie** [comment]
ah then thats what ill be downloading, thanks a lot!
