### ISSUE TITLE
Can you make a new doc?

### ISSUE THREAD

**Issue by NavaneethRao** [Nihlus/Launchpad#47]
I am not able to understand how to use it from the source. Also the links are not working.(link from launcher utlis)

**Comment by Nihlus** [comment]
Which link are you referring to? The docs are all up here on GitHub : https://github.com/Nihlus/Launchpad/wiki

**Comment by NavaneethRao** [comment]
https://github.com/Nihlus/Launchpad/wiki/Distributing-Launchpad-on-Windows is this for windows?

**Comment by NavaneethRao** [comment]
To generate a manifest, download this little app: Launcher Utilities. http://sharkman.asuscomm.com/files/public/Launchpad/Utilities/LaunchpadUtilities.zip this is not working

**Comment by Nihlus** [comment]
I had a temporary server outage - this has been fixed now.
