### ISSUE TITLE
What do you mean by 'root of the launchpad installation'

### ISSUE THREAD

**Issue by xXFrostyXx** [Nihlus/Launchpad#48]
What do you mean by 'root of the launchpad installation' in the in-depth wiki page for the config

**Comment by Nihlus** [comment]
Which part is that? In general, I'm referring to the topmost folder in the folder tree on the server where you're keeping the Launchpad-related files (game structure, etc).

**Comment by xXFrostyXx** [comment]
Under the ftp section in [launcherconfig.ini](https://github.com/Nihlus/Launchpad/wiki/LauncherConfig.ini-In-depth-explanation) it says "The URL pointing to the base directory of the launcher on your patching server." What do you mean by this? point it to the directory /srv/ftp, or put the root as the ftp folder so it shows the game/launcher folders? what.

**Comment by Nihlus** [comment]
The root of the FTP folder.

**Comment by xXFrostyXx** [comment]
Ok, thanks
