### ISSUE TITLE
Now its saying failed to connect to patch server

### ISSUE THREAD

**Issue by xXFrostyXx** [Nihlus/Launchpad#49]
the project is saying failed to connect to patch server.

here is my LauncherConfig.ini

[Local]
LauncherVersion = 0.3.0.24157
GameName = MultiTest
SystemTarget = Win64
GUID = 8637b68e-95c3-1941-b34b-7663ea148028
MainExecutableName = MultiTest

[Remote]
ChangelogURL = http://192.168.0.15/launchpad/changelog.html
Protocol = HTTP
FileRetries = 2
Username = anonymous
Password = anonymous
BufferSize = 8192

[FTP]
URL = ftp://192.168.0.15

[HTTP]
URL = http://192.168.0.15/launchpad

[BitTorrent]
Magnet = 

[Launchpad]
bOfficialUpdates = true
bAllowAnonymousStats = true

and my vsftpd is set to `local_root=/srv/`
I also have `anonymous_enable=YES`

Sorry if im bothering you with this.

**Comment by Nihlus** [comment]
Please join the Discord server for support requests instead. The github issues are more geared towards larger and confirmed issues with the launcher itself.

**Comment by xXFrostyXx** [comment]
@Nihlus link?

**Comment by Nihlus** [comment]
It's in the readme.

**Comment by Nihlus** [comment]
Oh, sorry, no, forgot to add it.
https://discord.gg/H5dF4x

**Comment by xXFrostyXx** [comment]
no? 
![no](https://user-images.githubusercontent.com/36825679/43931087-ce7d4eac-9c0a-11e8-8fae-d42c90be79fd.png)

**Comment by siegetech** [comment]
@Nihlus is there still a discord?
I'm having the same problem: Cant connect to patch server. I can connect hoverer trough any ftp or browser so it seems to be a config issue? Would love to get help

**Comment by Nihlus** [comment]
Sure is, @siegetech :)

https://discord.gg/0uvPPH2sOmcalj0K
