### ISSUE TITLE
A call to PInvoke function has unbalanced the stack

### ISSUE THREAD

**Issue by Trostka** [Nihlus/Launchpad#50]
Hello,

I tried to run your code to get a better understanding of how it works, and it threw the following exception on line 83 of Program.cs when it tried to run the GTK UI:

Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'GLibSharp!GLib.Marshaller+d_g_malloc::Invoke' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'

I first opened the project in VS 2017, and was prompted to download .NET 4.6.2 by several build errors. Those problems were solved after I downloaded that package, but running the project after I did so is when the exception first started popping up.

I have attached the full output log to this issue. Any advice that you might have for me would be deeply appreciated. :)
[Launchpad_OutputLog.txt](https://github.com/Nihlus/Launchpad/files/2487765/Launchpad_OutputLog.txt)

**Comment by Nihlus** [comment]
I saw that you could run it using Rider. Do you have the GTK#2 libraries installed? They can cause issues like this.

**Comment by Trostka** [comment]
As far as I'm aware, I don't have the GTK#2 libraries installed, though I don't know where to look for them. I've also never heard of Rider; do you mean that was something you used on my end, or is it something that I can download that would allow me to run the code?

**Comment by Trostka** [comment]
You used on your end*

**Comment by Nihlus** [comment]
Rider is an alternative to VS. I'm unsure what the issue is stemming from, I'm afraid.

**Comment by Fentonator** [comment]
This is in fact an actual bug, not just VS "behaving weirdly" in debug mode. More information about the topic in general, as well as an example of one possible cause to look for in terms of a fix, can be seen at https://stackoverflow.com/questions/3506796/pinvokestackimbalance-how-can-i-fix-this-or-turn-it-off.

Admittedly, I don't see any DllImport statements in the source, so this may be something a bit subtler about the interactions with the GTK# libraries, but hopefully this at least provides a starting point toward pinning it down.

**Comment by SankaDaVinci** [comment]
Im also getting the same issue even with GTK# Installed.

**Comment by Nihlus** [comment]
@SankaDaVinci You should not install GTK# anymore. Remove it from your system and compile the launcher from source.

**Comment by Reasp** [comment]
![image](https://user-images.githubusercontent.com/17028872/60422839-71e0fc00-9c1f-11e9-9c5b-e924bbc8b538.png)

Same issue. But project build successful

**Comment by IgnacioFDM** [comment]
This happens when you start with debugging enabled. If you start without debugging (ctrl + f5 in visual studio), or simply open the .exe manually, it will work fine.

**Comment by minichris** [comment]
If you wanna start with debugging enabled, but don't care about seeing PInvokeStackInbalences, you can follow the method from here (https://stackoverflow.com/a/9671751):
1. CTRL + ALT + E
2. Under "Managed Debugging Assistants" uncheck PInvokeStackImbalance.
Obviously, a proper fix is preferred though :)
