### ISSUE TITLE
vsftpd wont transfer large files through public IP

### ISSUE THREAD

**Issue by XZCendence** [Nihlus/Launchpad#55]
when I connect to it using the private IP (192.blah), it works perfectly, everything transfers super fast, BUT when I connect to it using the public IP port forwarded on my router, it connects and can transfer small files but completely fails with anything over 4000Kb

**Comment by Nihlus** [comment]
This sounds like an issue with your router or your vsftpd setup. I doubt it's with the launcher.

**Comment by XZCendence** [comment]
My router just port forwarded 21 to my internal IP and it connects and everything but no significant files can be transferred

**Comment by Nihlus** [comment]
It may be because of your router model, or some other configuration issue. I'm afraid this isn't something that can be fixed in the application without more information. Closing for now - if you find more details, feel free to reopen the issue.
